# read ALL paths generated by BN from database
if(F) {
    source('read_paths.r')
    print('reading paths')
    paths <- read.paths()
}

# read ways from database
if(F) {
    source('read_ways.r')
    ways <- read.ways()
}

# read ways and their statistical attributes from database
if(F) {
    source('read_ways.r')
    print('reading ways and attrs')
    df.ways.attrs <- read.ways.attrs(c('id','used_times','km','kmh'))
}

# retrive speed sequences of all paths
if(F) {
    speeds <- lapply(paths, path2speeds)
}

# deprecated. initialize used_times of ways as 0
if(F) {
    ways.used.times <- list()
    for(w in ways$id) {
        ways.used.times[w] <- 0
    }
}

# calculate used_times of ways in path
countways <- function(p) {
    ws <- p$ways
    for(w in ws) {
        #stat.ways[ways$id == w, "count"] <<- stat.ways[ways$id == w, "count"] + 1
        ways.used.times[w] <<- ways.used.times[[w]] + 1
    }
}

# calculate used_times of ALL ways from ALL paths
if(F) {
    lapply(paths, countways)
}

# plot hist of used_times of ALL ways
if(F) {
    a <- unlist(ways.used.times)
    hist(a)
    hist(a[a>0])
}

# generate data.frame of used_times of ways
if(F) {
    used_times <- unlist(ways.used.times)
    # all lengths should be equal to 52886
    if(length(ways.used.times) != length(used_times)) {
        print('error')
    }else {
        wid <- 1:length(used_times)
        df.ways <- data.frame(wid=wid, used_times=used_times)
    }
}

# statistical attribute sequence of ways in path
path2wayattrs <- function(p, attr) {
    ws <- p$ways
    ss <- rep(-1,length(ws))
    for(i in seq(ws)) {
        ss[i] <- df.ways.attrs[df.ways.attrs$id == ws[i], attr]
    }
    return(ss)
}

if(F) {
    ways.num <- length(df.ways.attrs$id)
    
    ways.used_times <- rep(0, ways.num)
    for(i in 1:ways.num) {
        ways.used_times[i] <- df.ways.attrs[df.ways.attrs$id == i, 'used_times']
    }
    ways.km <- rep(0, ways.num)
    for(i in 1:ways.num) {
        ways.km[i] <- df.ways.attrs[df.ways.attrs$id == i, 'km']
    }

    ways.kmh <- rep(0, ways.num)
    for(i in 1:ways.num) {
        ways.kmh[i] <- df.ways.attrs[df.ways.attrs$id == i, 'kmh']
    }
}

path2way.km <- function(p) {
    return(c(ways.km[p$ways]))
}

path2way.used_times <- function(p) {
    return(c(ways.used_times[p$ways]))
}

path2way.kmh <- function(p) {
    return(c(ways.kmh[p$ways]))
}

# retrive used_times sequences of all paths
if(F) {
    print('calculating used_times sequences')
    # paths.used_timeses <- lapply(paths, path2wayattrs, attr="used_times")
    paths.used_timeses <- lapply(paths, path2way.used_times)
}

# retrive length sequences of all paths
if(F) {
    print('calculating length sequences')
    # paths.lengths <- lapply(paths, path2wayattrs, attr="km")
    paths.lengths <- lapply(paths, path2way.km)
}

if(F) {
    paths.speeds <- lapply(paths, path2way.kmh)
}

path2cumlengths <- function(pl) {
    return(c(0, cumsum(pl)))
}

path2normlengths <- function(pl) {
    sl = sum(pl)
    return(pl/sl)
}

path2usedtimes_forplot <- function(pu) {
    return(c(pu, pu[length(pu)]))
}

if(F) {
    paths.norm.lengths <- lapply(paths.lengths, path2normlengths)
    paths.cum.lengths <- lapply(paths.lengths, path2cumlengths)
    paths.cum.norm.lengths <- lapply(paths.norm.lengths, path2cumlengths)
    paths.used_timeses.forplot <- lapply(paths.used_timeses, path2usedtimes_forplot)
}

plot.path.ut <- function(i) {
    # print(paths[[i]]$tid)
    tmp_cls <- paths.cum.lengths[[i]]
    tmp_cnls <- paths.cum.norm.lengths[[i]]
    tmp_uts <- paths.used_timeses.forplot[[i]]
    plot(tmp_cnls, tmp_uts, type='s') 
}

sample.stairs <- function(x,y,sp,sn,from) {
    max_x <- max(x)
    if(sn < 0) {
        sn <- ceiling(max_x / sp)
    }
    sx <- from
    cxi <- 1
    cx <- x[cxi]
    cy <- 0
    s <- rep(0, sn)
    si <- 0
    repeat {
        while(sx < cx) {
            si <- si + 1
            s[si] <- cy
            if(si >= sn) {
                break
            }
            sx <- sx + sp            
        }
        if(si >= sn) {
            break
        }
        cxi <- cxi + 1
        if(cxi > length(x)) {
            break
        }
        cx <- x[cxi]
        cy <- y[cxi-1]
    }
    return(s)
}

sp <- 0.001
sn <- 1000
from <- 0

avg.path.ut <- function() {
    paths.num = length(paths)
    avg.uts <- rep(0, sn)
    for(i in 1:paths.num) {
        avg.uts <- avg.uts + sample.stairs(paths.cum.norm.lengths[[i]], paths.used_timeses.forplot[[i]], sp, sn, from)
    }
    return(avg.uts / paths.num)
}

plot.avg.uts <- function(avg.uts) {
    x11()
    plot(seq(sp,sp*sn,sp), avg.uts, type='l')
}

if(F) {
    avg.uts <- avg.path.ut()
    plot.avg.uts(avg.uts)
}














