source('ways_clust.r')
ways.sf <- read.ways.sf()
mat.sf <- read.mat.sf(100, ways.sf, F)
mat.sf.all <- read.mat.sf(100, ways.sf, T)

som.iter.res <- load.var('res10.RData')
plot.grid.ggplot(som.iter.res)
cato.legend()
map.heat(som.iter.res$heat)
map.heat(u.mat.som(som.iter.res$code, 10, 10))
hist.catos()
hist.catos.freq()
hist.catos.kmh()
hist.catos.km()
hist.catos.npd()

load.sf.h()
load.catos()
diff.catos <- find.opp.diff.cato(catos.h)
ways.sf.h0811(40202)
